# Generated by Django 5.0.4 on 2026-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(choices=[('shopping-cart', 'Alimentation'), ('car', 'Transport'), ('home', 'Logement'), ('heart', 'Santé'), ('gamepad', 'Loisirs'), ('wifi', 'Abonnements'), ('shirt', 'Vêtements'), ('book', 'Éducation'), ('plane', 'Voyages'), ('briefcase', 'Salaire'), ('circle-dollar-sign', 'Autres')], default='circle-dollar-sign', max_length=50)),
                ('is_default', models.BooleanField(default=True, help_text="Indique que cette catégorie est prédéfinie par l'application.")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
    ]
