# Generated by Django 5.0.4 on 2026-03-31 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Toujours positif. Le type de transaction indique le sens du mouvement.', max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar américain ($)'), ('GBP', 'Livre sterling (£)'), ('CHF', 'Franc suisse (CHF)'), ('CAD', 'Dollar canadien (CA$)'), ('JPY', 'Yen japonais (¥)')], default='EUR', max_length=3)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Revenu'), ('EXPENSE', 'Dépense'), ('SAVINGS', 'Épargne'), ('REIMBURSEMENT', 'Remboursement'), ('TRANSFER', 'Transfert')], max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel')], help_text='Obligatoire uniquement si is_recurring est True.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
